-- Add sample data directly to creator_listings table (bypassing foreign key issues)
INSERT INTO public.creator_listings (profile_id, display_name, niche, price_range, rating, total_reviews, total_campaigns, is_verified, badge_level) VALUES
  ('profile-maria-silva', 'Maria Silva', 'fashion', 'Mid-range', 4.8, 24, 15, true, 'gold'),
  ('profile-joao-santos', 'João Santos', 'tech', 'Premium', 4.9, 31, 22, true, 'platinum'),
  ('profile-ana-costa', 'Ana Costa', 'fitness', 'Mid-range', 4.6, 18, 12, false, 'silver'),
  ('profile-pedro-lima', 'Pedro Lima', 'gaming', 'Budget-friendly', 4.2, 12, 8, false, 'bronze'),
  ('profile-carla-nunes', 'Carla Nunes', 'food', 'Mid-range', 4.7, 22, 14, true, 'gold'),
  ('profile-rafael-torres', 'Rafael Torres', 'travel', 'Premium', 4.9, 28, 19, true, 'platinum'),
  ('profile-lucia-oliveira', 'Lucia Oliveira', 'beauty', 'Budget-friendly', 4.5, 15, 10, false, 'silver'),
  ('profile-bruno-alves', 'Bruno Alves', 'fitness', 'Mid-range', 4.4, 19, 13, false, 'bronze'),
  ('profile-fernanda-rocha', 'Fernanda Rocha', 'pets', 'Budget-friendly', 4.3, 8, 5, false, 'bronze'),
  ('profile-diego-ferreira', 'Diego Ferreira', 'business', 'Premium', 4.8, 33, 25, true, 'platinum'),
  ('profile-isabela-santos', 'Isabela Santos', 'lifestyle', 'Mid-range', 4.7, 26, 18, true, 'gold'),
  ('profile-leonardo-costa', 'Leonardo Costa', 'sports', 'Premium', 4.6, 21, 16, false, 'silver'),
  ('profile-amanda-silva', 'Amanda Silva', 'music', 'Budget-friendly', 4.4, 14, 9, false, 'bronze'),
  ('profile-guilherme-pereira', 'Guilherme Pereira', 'automotive', 'Premium', 4.8, 29, 20, true, 'platinum'),
  ('profile-camila-rodrigues', 'Camila Rodrigues', 'parenting', 'Mid-range', 4.5, 17, 11, false, 'silver'),
  ('profile-thiago-almeida', 'Thiago Almeida', 'education', 'Budget-friendly', 4.3, 13, 7, false, 'bronze'),
  ('profile-priscila-martins', 'Priscila Martins', 'health', 'Mid-range', 4.6, 23, 14, true, 'gold'),
  ('profile-carlos-nascimento', 'Carlos Nascimento', 'finance', 'Premium', 4.9, 35, 27, true, 'platinum'),
  ('profile-juliana-ferreira', 'Juliana Ferreira', 'diy', 'Budget-friendly', 4.2, 11, 6, false, 'bronze'),
  ('profile-rodrigo-souza', 'Rodrigo Souza', 'comedy', 'Mid-range', 4.7, 25, 17, true, 'gold'),
  ('profile-larissa-lima', 'Larissa Lima', 'photography', 'Premium', 4.8, 30, 21, true, 'platinum'),
  ('profile-felipe-santos', 'Felipe Santos', 'cooking', 'Mid-range', 4.5, 19, 12, false, 'silver'),
  ('profile-tatiana-oliveira', 'Tatiana Oliveira', 'books', 'Budget-friendly', 4.4, 16, 8, false, 'bronze'),
  ('profile-ricardo-silva', 'Ricardo Silva', 'motivation', 'Premium', 4.9, 32, 24, true, 'platinum'),
  ('profile-patricia-costa', 'Patricia Costa', 'crafts', 'Mid-range', 4.6, 20, 13, false, 'silver'),
  ('profile-daniel-rodrigues', 'Daniel Rodrigues', 'nature', 'Budget-friendly', 4.3, 12, 7, false, 'bronze'),
  ('profile-vanessa-alves', 'Vanessa Alves', 'skincare', 'Premium', 4.8, 28, 19, true, 'gold'),
  ('profile-marco-pereira', 'Marco Pereira', 'dance', 'Mid-range', 4.7, 24, 15, true, 'silver'),
  ('profile-carolina-santos', 'Carolina Santos', 'architecture', 'Premium', 4.9, 31, 22, true, 'platinum'),
  ('profile-andre-lima', 'André Lima', 'meditation', 'Budget-friendly', 4.4, 15, 9, false, 'bronze')
ON CONFLICT (profile_id) DO NOTHING;