// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bujxejjngqjrnwtjcylu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1anhlampuZ3Fqcm53dGpjeWx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTYyMzMsImV4cCI6MjA2NTQ3MjIzM30.NYSnEoheI0I8pvVrJ91hQS14TMyADwOFz4Itbqj9-mQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);